version: '3.8'
services:
  api:
    image: docker-java-jar
    ports:
      - '8888:8888'
  ui:
    image: docker-react
    ports:
      - '3006:3005'
    volumes:
      - ./ui/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/public/index.html:/usr/share/nginx/html/index.html
      - ./ui/public/css:/usr/share/nginx/html/css
  dataBase:
    image: postgres:15
    environment:
      POSTGRES_DB: "sber"
      POSTGRES_USER: "sber"
      POSTGRES_PASSWORD: "passWORD"
    ports:
      - "5431:5432"
    restart: always

