create table status
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code varchar(15) not null unique,
    name varchar(20) not null,
    CONSTRAINT pk_status PRIMARY KEY (id)
);

create table documents
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type         varchar(20),
    organization varchar(128),
    description  varchar(512),
    patient      varchar(128),
    date         TIMESTAMP,
    status bigint references status,
    CONSTRAINT pk_documents PRIMARY KEY (id)
);

insert into status
(code, name)
values ('NEW', 'Новый'),
       ('IN_PROCESS', 'В обработке'),
       ('ACCEPTED', 'Принят'),
       ('DECLINED', 'Отклонен');

insert into documents
(type, organization, description, patient, date, status)
values ('Направление',
        'ОГБУЗ Саянская городская больница',
        'Направление на МСЭ',
        'Иванов Иван Иванович',
        '03.11.2023',
        '1');

