server:
  port: 8888

logging:
  config: classpath:logback-spring.xml

cors:
  allow: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/sber
    username: sber
    password: passWORD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:29092